const errorMessageObj = {
    username: "이름을 입력해주세요.",
    id: "아이디를 입력해주세요.",
    pw: "비밀번호를 입력해주세요.",
    pqssword: "비밀번호를 입력해주세요.",
    birthday: "생년월일을 입력해주세요.",
    telnumber: "전화번호를 입력해주세요.",
    nickname: "별명을 입력해주세요.",
    email: "이메일을 입력해주세요.",
    drivername: "기사이름을 입력해주세요.",
    level: "등급을 선택해주세요.",
    nationcodeidx: "국가타입을 선택해주세요.",
    areacodeidx: "지역코드를 선택해주세요.",
    tourcode: "투어코드를 선택해주세요",
    operatingtime: "영업시간을 선택해주세요.",
    address: "주소를 입력해주세요",
    admissionfee: "입장료를 입력해주세요.",
    koreanname: "국가한국이름을 입력해주세요.",
    englishname: "국가영어이름을 입력해주세요.",
    code3: "국가코드 3자리를 입력해주세요.",
    code2: "국가코드 2자리를 입력해주세요.",
    tourname: "관광지명을 입력해주세요",
    tourtype: "투어 종류를 선택해주세요.",
    touridx: "관광지코드를 입력해주세요.",
    tourdays: "투어 일수를 입력해주세요.",
    tourstartday: "투어 시작일을 입력해주세요.",
    purchasedate: "구매일자를 선택해주세요",
    purchasetype: "구매방식을 선택해주세요",
    price: "금액을 입력해주세요.",
    purchaseuser: "구매자id를 입력해주세요",
    title: "제목을 입력해주세요",
    contents: "내용을 입력해주세요.",
    contactNumber: "전화번호를 입력해주세요",
    sendContent: "내용을 입력해주세요.",
    sidocode: "시도 코드를 입력해주세요",
    sidoname: "시도 이름을 입력해주세요",
    areacode: "지역 코드를 입력해주세요",
    areaname: "지역 이름을 입력해주세요.",
    sendEmail: "이메일을 입력해주세요.",
    scripttitle: "스크립트명을 입력해주세요.",
    scriptcontents: "스크립트 내용을 입력해주세요.",
};

export default errorMessageObj;
